### ISSUE TITLE
Make an English translation of "(Nunca) Ouvi Falar de Rust"

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/bltavares-presentations#1]
- [x] Initial translation pass
- [x] Editing pass
    - [x] Handle any TODO/FIXME/XXX comments that Erich can do himself
- [ ] Questions/requests for Bruno
    - [ ] Resolution for FIXME/TODO items
    - [ ] Localize Nickel walkthrough assets?
    - [ ] Anything else you'd like in the translation?

**Comment by ErichDonGubler** [comment]
@bltavares, the [WIP](https://github.com/ErichDonGubler/bltavares-presentations/tree/traducao/nunca-ouvi-falar-de-rust.wip) branch in this fork has had an initial translation pass done in your `index.org` file, but methinks you probably don't want it there when I actually make a PR. How would you like the English translation stored in this repo?

**Comment by bltavares** [comment]
Nice work so far (:

To store the file I guess either a new folder with the name of the presentations as the other presentations (as each of the index.html gets automatically picked up) or a `index.en.org` + `index.en.html`. I don't have much strong opinions on it.

If you would like, I could regenerate the html at some point, and manually apply the words coloring (as it is not done through `org-mode`, sadly)

**Comment by ErichDonGubler** [comment]
An `index.en.org` sounds like an easy win. 

How is the coloring applied? I'm more than happy to make sure that that's consistent too. :) Also, how to generate  HTML?

**Comment by bltavares** [comment]
That is the boring (and a bit complex) part haha

I'm using `spacemacs` with [reveal.js org-mode extension](https://github.com/bltavares/dot-files/blob/master/spacemacs.d/init.el#L43-L46) to generate the html file.

With the following sequence I get an html file: `Space m e e R R`

Then I visit the html file and add a couple of `<span class="showup">` and replace each `Rust` word with a span with a class available on (extra.css)[https://github.com/bltavares/presentations/blob/gh-pages/nunca-ouvi-falar-de-rust/extra.css]

It is a bit more cumbersome than I'd recommend to someone... Sorry about that. Don't worry if you don't feel like configuring this all to generate the final slides. Just let me know and I can create it (:

**Comment by ErichDonGubler** [comment]
I'm closing this issue in favor of the pull request I [just created](https://github.com/bltavares/presentations/pull/8) for these changes. :) I'll move over any information I think is relevant -- if you want to include anything else, feel free to add it as a comment!
